### ISSUE TITLE
Failure when the helmrepository and the helmrelease are in different namespaces

### ISSUE THREAD

**Issue by xavidop** [christianh814/mta#12]
Hello,

We found an issue where we have the helmrelease in namespace X and the helmrepository in namespace Y `mta` fails to migrate the helmrelease with error:
```bash
FATA[0002] helmrepositories.source.toolkit.fluxcd.io "Y" not found
```
The command we run is:
```bash
mta helmrelease --name my-helmrelease --namespace X
```

**Comment by christianh814** [comment]
Updating here from the Discord https://discord.com/channels/1138942074998235187/1280808653280116818/1282608495409238038

Looks like a version mismatch https://github.com/akuity/mta/blob/main/pkg/utils/utils.go#L11C56-L12C1

@nitishfy we might consider making it "backwards compatible" for whichever version Flux currently supports.

**Comment by christianh814** [comment]
Looks like I was mistaken. The issue is that `mta` assumes HelmRelease and HelmRepo objects are in the same namespace.

**Comment by xavidop** [comment]
yeah that was my thought too

**Comment by nitishfy** [comment]
The fix is out now!
