### ISSUE TITLE
Failure when the helmrepository and the helmrelease are in different namespaces 

### ISSUE THREAD

**Issue by xavidop** [christianh814/mta#16]
Hello,

We found an issue where we have the helmrelease in namespace X and the helmrepository in namespace Y `mta` fails to migrate the helmrelease with error:
```bash
FATA[0002] helmrepositories.source.toolkit.fluxcd.io "Y" not found
```
The command we run is:
```bash
mta helmrelease --name my-helmrelease --namespace X
```

**Comment by xavidop** [comment]
@nitishfy do you have any update here?

**Comment by nitishfy** [comment]
working on this.

**Comment by xavidop** [comment]
thank you!
